name: pendulum
description: Dart/Flutter implementation of a double pendulum https://www.youtube.com/watch?v=DMOK5BS6KJw

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"